src/blog/urls.py
from django.urls import path
from blog.views import(
    create_blog_view,
    detail_blog_view,
    edit_blog_view,
    quiz_view,
    quiz_data_view,
    save_quiz_view,
    bookmark_blog_view,
)

app_name = 'blog'

urlpatterns = [
    path('create/', create_blog_view, name="create"),
    path('<slug>/', detail_blog_view, name="detail"),
    path('<slug>/edit', edit_blog_view, name="edit"),
    path('<slug>/quiz', quiz_view, name="quiz"),
    path('<slug>/quiz/data', quiz_data_view, name="quiz-data"),
    path('<slug>/quiz/save', save_quiz_view, name="save-data"),
    path('<slug>/bookmark', bookmark_blog_view, name="bookmark-topic"),
]

src/mysite/urls.py
from django.contrib import admin
from django.urls import re_path, path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
  re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
  re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

from personal.views import (
    home_screen_view,
    topics_view,
    success_view,
    error_view,
    contact_view,
    privacy_view,
    faq_view,
    about_view
)

from preposttest.views import(
    pretest_view,
)

from user.views import(
    registration_view,
    login_view,
    logout_view,
    account_view,
    must_authenticate_view,
    detail_view,
    reading_view,
    cert_pdf_view,
    statistic_view,
    test_recaptcha_view,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_screen_view, name="home"),
    path('about/', about_view, name='about'),
    path('blog/', include('blog.urls','blog')),
    path('preposttest/', include('preposttest.urls','preposttest')),    
    path('register/', registration_view, name="register"),
    path('logout/', logout_view, name="logout"),
    path('login/', login_view, name="login"),
    path('account/', account_view, name="account"),
    path('accounts/', include('allauth.urls')),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('topics/', topics_view, name="topics"),
    path('detail/', detail_view, name='detail'),
    path('statistics/', statistic_view, name='statistics'),
    path('cert_pdf/<title>/', cert_pdf_view, name='cert_pdf'),
    path('reading/', reading_view, name='reading'),
    path('contact/', contact_view, name='contact'),
    path('faq/', faq_view, name='faq'),
    path('privacy/', privacy_view, name='privacy'),
    path('test-recaptcha/', test_recaptcha_view, name='test_recaptcha'),

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),

    path("success/", success_view, name="success"),
    path("error/", error_view, name="error"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/preposttest/urls.py
from django.urls import path
from preposttest.views import(
    pretest_view,
    pretest_data_view,
    save_pretest_view,
)

app_name = 'preposttest'

urlpatterns = [
    path('<slug>/pretest', pretest_view, name="pretest"),
    path('<slug>/pretest/data', pretest_data_view, name="pretest-data"),
    path('<slug>/pretest/save', save_pretest_view, name="save-data"),
]

src/personal/models.py
from django.db import models

class Faq(models.Model):
    FAQquestion             = models.TextField()
    FAQanswer               = models.TextField()

    def __str__(self):
        return self.FAQquestion

def upload_location(instance, filename):
    file_path = 'staff/{name}-{filename}'.format(
        author_id=str(instance.author.id), title=str(instance.title), filename=filename
    )
    return file_path

class Staff(models.Model):
    name                    = models.TextField(blank=False)
    image                   = models.ImageField(upload_to=upload_location, null=False, blank=False)
    education               = models.TextField(blank=False)
    title                   = models.TextField(blank=False)
    phone                   = models.TextField()
    email                   = models.TextField()
    detail                  = models.TextField(blank=False)



    

src/personal/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from operator import attrgetter

from answer.models import Result
from preposttest.models import ResultPrePostTest
from user.models import Account
from blog.models import Sessions, BlogPost
from personal.models import Faq
from preposttest.models import PreTest

from django.shortcuts import redirect, render

import mailchimp_marketing as MailchimpMarketing
from mailchimp_marketing import Client
from mailchimp_marketing.api_client import ApiClientError
from django.conf import settings
from django.core.mail import send_mail

from django import template

import math

register = template.Library()

# Create your views here

api_key = "b92391bc4cb971e974c69df7794ff9f7-us21"
list_id = "c06a45ad70"
 
# function to manage subscriber
 
def success_view(request):
    return render(request, 'personal/success_newsletter.html')
 
def error_view(request):
    return render(request, 'personal/error_newsletter.html')

def topics_view(request):
    context = {}
    
    sections = Sessions.objects.all().order_by('display_order')
    section_topics_dict = {}
    temp_result = Result(score = 0.00)
        
    if request.user.is_authenticated == True:
        email = request.user.email
    else:
        email = ""

    if request.method=="POST":
        pick_section=request.POST.get('pick_section')
        result = Result.objects.filter(user__email__contains=email)
        context['result'] = result
    else :
        pick_section = Sessions.objects.order_by('display_order').first().title
        result = Result.objects.filter(user__email__contains=email)
        context['result'] = result

    section_info = {}    

    for section in sections:
        section_dict = {}
        section_dict['section'] = section
        section_dict['section_order'] = section.display_order

        section_dict['pretest'] = section.pretest.filter(test_type='pretest').first()
        section_dict['posttest'] = section.pretest.filter(test_type='posttest').first()

        
        quiz_passed = 0
        process = 0

        if request.user.is_authenticated:
            pretest_found = ResultPrePostTest.objects.filter(pre_test__session=section, user=request.user, pre_test__test_type="pretest").exists()
            posttest_found = ResultPrePostTest.objects.filter(pre_test__session=section, user=request.user, pre_test__test_type="posttest").exists()

            result = Result.objects.filter(user = request.user, quiz__session = section)
            for r in result:
                if r.score == 100: quiz_passed=quiz_passed+1
        else:
            pretest_found = False
            posttest_found = False
        
        if quiz_passed != 0:
            topics_count = BlogPost.objects.filter(session=section).count()
            process = (quiz_passed/topics_count)*100

        section_info[section] = process

        if process != 100:
            posttest_status = 1
        else:
            if posttest_found:
                posttest_status = 3
            else:
                posttest_status = 2

        section_dict['pretest_found'] = pretest_found
        section_dict['posttest_status'] = posttest_status

        blog_posts = section.get_blog()
        section_dict['blog_posts'] = []

        for index, blog_post in enumerate(blog_posts):
            previous_results = Result(score=0.00)
            
            if request.user.is_authenticated:
                result = Result.objects.filter(quiz=blog_post, user=request.user).first()
                if result is None:
                    result = Result(score=0.00)

                if index == 0:
                    try:
                        resultPretest = ResultPrePostTest.objects.get(pre_test__session=section, user=request.user, pre_test__test_type="pretest")
                        previous_results = Result(score=100.00)
                    except ResultPrePostTest.DoesNotExist:
                        previous_results = Result(score=0.00)
                        result = Result(score=0.00)
                else:
                    if temp_result is None:
                        previous_results = Result(score=0.00)
                    else:
                        previous_results = temp_result
            else:
                result = Result(score=0.00)
                if index == 0:
                    previous_results = Result(score=100.00)
                else:
                    previous_results = temp_result

            print("\n\nscore is")
            print(previous_results)

            
            wordCount = len(blog_post.body.split())
            readingTime = math.ceil(wordCount/200)

            section_dict['blog_posts'].append((blog_post, result.score if result else 0, previous_results, readingTime))
            
            temp_result = result

        section_topics_dict[section.title] = section_dict
    
    context['section_topics_dict'] = section_topics_dict

    # result_filtered = result.filter(quiz__session__title__contains=pick_section)
    # picked_section=Sessions.objects.filter(title__icontains = pick_section)

    topics = BlogPost.objects.filter(session__title = pick_section).order_by('display_order')

    context['section_info'] = section_info
    context['sections'] = sections
    context['topics'] = topics

    return render(request, "personal/topics.html", context)

def about_view(request):
    return render(request, 'personal/about.html')

def home_screen_view(request):
    context = {}

    sections = Sessions.objects.all()
    context['sections'] = sections

    if request.user.is_authenticated == True:
        username = request.user.username
        email = request.user.email
    else:
        username = ""
        email = ""

    context['username'] = username
    context['email'] = email

    if request.method == "POST":
        # getting users input from the form
        email = request.POST['email']
        username = request.POST['username']
 
        # initializing the mailchimp client with api key
        mailchimpClient = Client()
        mailchimpClient.set_config({
            "api_key": api_key,
        })
 
        userInfo = {
            "email_address": email,
            "status": "subscribed",
            "merge_fields": {
                "FNAME": username,
                "LNAME": "",
            }
        }
 
        try:
            # adding member to mailchimp audience list
            mailchimpClient.lists.add_list_member(list_id, userInfo)
            print("Success")
            
            # return HttpResponse('Subscribed Successfully')
            
        except ApiClientError as error:
            print(error.text)

            # return redirect("error")
        
    return render(request, 'personal/home.html', context)

def contact_view(request):
    if request.user.is_authenticated == True:
        username = request.user.username
        email = request.user.email
    else:
        username = ""
        email = ""

    context = {}
    context['username'] = username
    context['email'] = email

    if request.method == "POST":
        email = request.POST['email']
        username = request.POST['name']
        content = request.POST['content']

        subject = 'Inquiry from ' + username
        message = 'An inquiry from\n' + username + ' ('+ email +')\n\n'+ content
        email_from = settings.EMAIL_HOST_USER
        send_mail( subject, message, email_from, [email_from] )
    return render(request, 'personal/contact.html', context)

def faq_view(request):
    if 'q' in request.GET:
        q = request.GET['q']
        faq = Faq.objects.filter(FAQquestion__icontains=q)
    else:
        faq = Faq.objects.all()
    context = {
        'faq': faq
    }
    return render(request, 'personal/faq.html', context)


def privacy_view(request):
    return render(request, 'personal/privacy.html')

src/personal/templates/personal/error_newsletter.html
<head>
	<meta charset="utf-8">
	<title>Failure</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
		integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>

<body>
	<div class="jumbotron jumbotron-fluid">
		<div class="container">
			<h1 class="display-4">Uh oh!</h1>
			<p class="lead">Contact the developer</p>




			<form class="" action="/error" method="post">
				<button class="btn btn-lg " type="submit"
						name="button">Try again</button>
			</form>
		</div>
	</div>
</body>

src/personal/templates/personal/success_newsletter.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
	<title>Subscribed to newsletter - Dementia Learn</title>
	<meta charset="utf-8">
	<title>successfully</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
		integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>

<body>
	<div class="jumbotron jumbotron-fluid">
		<div class="container">
			<h1 class="display-4">Awesom</h1>
			<p class="lead">You are successful to signup in newsletter website,
				please look forward.</p>




		</div>
	</div>
</body>

</html>

src/personal/templates/personal/topics copy.html
{% extends 'base.html' %}


{% block content %}


<style type="text/css">
    .form-signin {
    width: 100%;
    max-width: 900px;
    padding: 30px;
    margin: auto;
    }
    .form-signin .form-control {
    /* position: relative; */
    box-sizing: border-box;
    height: auto;
    padding: 10px;
    font-size: 18px;
    margin-bottom: 20px;
    }
    .form-signin .form-control:focus {
    z-index: 2;
    }
    .form-signin input[type="email"] {
    margin-bottom: 10px;
    border-radius: 10px;
    }
    .form-signin input[type="text"] {
    margin-bottom: 20px;
    border-radius: 10px;
    }
    
    /* Style the tab */
.tab {
  float: left;
  {% comment %} background-color: #f1f1f1; {% endcomment %}
  width: 20%;
  padding-right: 20px;
  margin-top: 30px;
  margin-left: 30px;
  min-width: 180px;
  overflow: visible;
}
.card-body{
	padding: 15px;
	word-wrap: break-word;
	border-bottom-right-radius: 25px;
	border-bottom-left-radius: 25px;
}
.nodeco{
	text-decoration: none;
}
.nodeco:hover{
	text-decoration: none;
}
/* Style the buttons inside the tab */
.tab button {
  display: block;
  background-color: inherit;
  color: black;
  padding: 15px 15px;
  width: 100%;
  border: 1px #b5b5b5 solid;
  outline: none;
  text-align: left;
  cursor: pointer;
  transition: 0.3s;
  font-size: 17px;
  margin-bottom: 10px;
  border-radius: 10px;
}

/* Change background color of buttons on hover */
.tab button:hover {
  background-color: #c2dafbc3;
  color: #22559e;
}

/* Create an active/current "tab button" class */
.tab button.active {
background-color: #c2dafbc3;
box-shadow: 0px 10px 20px #a2a2a27b;

}
#pretestButton{
	margin-left: 0px;
	width: 30%;  
	margin-top: 20px; 
	text-align: center; 
	height: 400px; 
	background-color: #0C6DFD; 
	display: flex; 
	justify-content: center; 
	align-items: center;
	cursor: pointer;
	margin-right: 3%;
}
/* Style the tab content */
.tabcontent {
  {% comment %} float: left; {% endcomment %}
  {% comment %} width: 65%; {% endcomment %}
  {% comment %} box-shadow: 0px 10px 20px #a2a2a27b; {% endcomment %}
{% comment %} border-radius: 10px; {% endcomment %}
}
.button{
  box-shadow: 0px 4px 20px 0px #49c628a6;
  background-image: linear-gradient(135deg, #70F570 10%, #49C628 100%);
  border: none;
}
.card-section:hover {
	box-shadow: -2px -2px 6px rgba(255, 255, 255, .5), -2px -2px 4px rgba(255, 255, 255, .3), 2px 2px 2px rgba(255, 255, 255, .05), 2px 2px 4px rgba(0, 0, 0, .1);
}
.card-section:active  {
	box-shadow: inset -2px -2px 6px rgba(255, 255, 255, .7), inset -2px -2px 4px rgba(255, 255, 255, .5), inset 2px 2px 2px rgba(255, 255, 255, .075), inset 2px 2px 4px rgba(0, 0, 0, .15);
}
.card-section{
	background-color: #F3F0F1;
	width: 100%;
	margin: 30px;
	padding: 10px;
	border: transparent;
	transition: .2s ease-in-out;
	box-shadow: -6px -6px 14px rgba(255, 255, 255, .7),
		  -6px -6px 10px rgba(255, 255, 255, .5),
		  6px 6px 8px rgba(255, 255, 255, .075),
		  6px 6px 10px rgba(0, 0, 0, .15);
	border-radius: 25px;
}
#container{
margin-top: 20px;
width: 30%; 
margin-right: 3%; 
margin-bottom: 20px;
}
.smallScreen{
	display: none;
}
.bigScreen{
	display: block;
}
@media only screen and (max-width: 1005px) {
    #container{
		width: 45%; 
	}
	#pretestButton{
		width: 45%;
	}

}
@media only screen and (max-width: 740px) {
	.smallScreen {
		display: block;
    } 
	.bigScreen{
		display: none;
	}
}
@media only screen and (max-width: 510px) {
	#container{
		width: 90%; 
		margin-left:10px;
	}
	#pretestButton{
		width: 90%;
		height: 100px;
		margin-left:10px;
		margin-top: 10px;
		margin-bottom: 15px;
	}
}
select.mySelectArrow{
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
    color: grey;
    width: 100%;
    padding: 10px 20px;
    font-size: 15px;

}
select.mySelectArrow option {
    color: #000;
    padding: 0 10px;
}
.select:after {
    content: "▼";
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    font-size: 15px;
    {% comment %} border: 1px solid #565656; {% endcomment %}

    color: black;
    padding: 15px 15px;
    pointer-events: none;
}
.select {
    position: relative;
    width: 90%;
	margin-left: 5%;
	margin-right: 5%;
	margin-top: 10px;
}

a.disabledLink {
    position: relative;
    display: inline-block;
}

a.disabledLink .overlay {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
	align-items: center;
    justify-content: center;
	border-radius: 25px;
    background-color: rgba(0, 0, 0, 0.5); /* Black with 50% opacity */
    z-index: 2;
}

</style>

<title>Topics - Dementia Learn</title>
<div style="height: auto; border:solid">
	<div class="fill p-3" style="display: flex; margin-top: -100px; justify-content: center; align-items: center; position:relative; background-color: #F2A5A5; height: 320px;">
        <h1 class="p-3" style="color: white; font-weight: 600;margin-top: 70px; ">Browse our section</h1>
    </div>
	<div class="select smallScreen">
		<select id="sectionSelect" class="mySelectArrow" style="border-radius: 10px; height: 50px;">

		  {% for section, score in section_info.items %}
		  {% if forloop.counter == 1 %}
		  <option class="tablinks" onclick="openSet(event, '{{ section.display_order }}')">{{ section.title }}</option>
		  {% else %}
		  <option class="tablinks"  onclick="openSet(event, '{{ section.display_order }}')">{{ section.title }}</option>
			{% endif %}
		  {% endfor %}
		</select>
	  </div>
		<div class="tab bigScreen" style="border:solid">
				{% for section, score in section_info.items %}
				<button class="tablinks" style="width: 100%;" onclick="openSet(event, '{{ section.display_order }}')" 
				{% if forloop.counter == 1 %}
					id="defaultOpen"
				{% endif %}>
					<div class="column" style="width: 100%; ">
						<h5>{{ section.display_order }}</h5>
					</div>
					<div>
				<progress style="width: 100%;" id="file" value="{{ score }}" max="100"> {% widthratio count.result count.topic 100 %}% </progress>
				  <p>{{ score }}% complete</p>     
			</div>
		</button>
		{% endfor %} 
	{% comment %} </div>   {% endcomment %}
  		</div>
   	<!-- Sections -->
	{% for section, section_info in section_topics_dict.items %}
	<div id='{{ section_info.section.display_order }}' class="tabcontent">
			<div style="display: flex; flex-wrap: wrap; padding-left: 2%; border-left: 2px #b5b5b5 solid;">
				
				{% if not section_info.pretest.slug %}
				<div class="card-section " id="pretestButton" style="background-color: #FF0000;">
					<h5 style="color: white; cursor: pointer;">Contact admin: Pretest link not found</h5>
				</div>
				{% elif request.user.is_superuser %}
				<div class="card-section" style="background-color:#990033;" id="pretestButton" onclick="location.href='{% url 'preposttest:pretest' section_info.pretest.slug %}';">
					<h5 style="color: white; cursor: pointer;">Pretest admin preview. Results won't be saved</h5>
				</div>
				{% elif not section_info.pretest_found %}
				<div class="card-section " id="pretestButton" onclick="location.href='{% url 'preposttest:pretest' section_info.pretest.slug %}';">
					<h5 style="color: white; cursor: pointer;">Click HERE to do the pretest {{ section_info.pretest.slug }}</h5>
				</div>
				{% else %}
				<div class="card-section " id="pretestButton" onclick="alertPopUp('Pretest can only be done once')" style="background-color: #09DD91;">
					<h5 style="color: white; cursor: pointer;">PRETEST DONE</h5>
				</div>
				{% endif%}

				{% for blog_post, score, prev_result, reading_time in section_info.blog_posts %}
					<div id="container" class="p-0">
						{% if prev_result.score == 100.00 or request.user.is_superuser %}

						<a class="nodeco" href="{% url 'blog:detail' blog_post.slug %}">
							<div class="card-section m-auto p-0" style="position: relative; height:400px;">
								<img class="card-img-top" src="{{blog_post.image.url}}" style="width: 100%; height: 200px; border-top-left-radius: 25px; border-top-right-radius: 25px; object-fit: cover;">
								<div class="card-body mt-0 mb-0">
									<h5 class="text-dark " style="font-size: 18px;">{{blog_post.title}}</h5>
									<p style="color: grey; margin-bottom: 8px;">{{reading_time}} minutes</p> 
										  {% if request.user.is_superuser %}
										  <a href="{% url 'blog:edit' blog_post.slug %}" class="btn btn-primary">Update</a>
										 {% else %} 
										  <progress style="width: 100%; margin-top: -5px;" id="file" value="{{ score }}" max="100"> {% widthratio count.result count.topic 100 %}% </progress>
										  <p class="text-dark ">{{ score }}% complete</p>     
										  {% endif %}
								</div>
							</div>
						</a>

						{% else %}

							<a href="#" onclick="alertPopUp('Make sure you have done the previous quizzes or pretest')" style="width: 100%; border: solid;" class="nodeco locked disabledLink">
								<div class="py-0 card-section m-auto p-0 position: relative; display: inline-block;" style="position: relative; height:400px; border: solid;">
									<img class="card-img-top" src="{{blog_post.image.url}}" style="height: 200px; border-top-left-radius: 25px; border-top-right-radius: 25px; object-fit: cover;">
										<div><img class="overlay" style="padding: 35%; object-fit: contain;" src="https://i.ibb.co/d5wkdQf/lock-outline-24px.png" alt="lock" width="10%" border="0"></div>
									<div class="card-body mt-0 mb-0">
										<h5 class="text-dark " style="font-size: 18px;">{{blog_post.title}}</h5>
										<p style="color: grey; margin-bottom: 8px;">{{reading_time}} minutes</p> 
											  {% if request.user.is_superuser %}
											  <!-- <a href="{% url 'blog:edit' blog_post.slug %}" class="btn btn-primary">Update</a> -->
											 {% else %} 
											  <progress style="width: 100%; margin-top: -5px;" id="file" value="{{ score }}" max="100"> {% widthratio count.result count.topic 100 %}% </progress>
											  <p class="text-dark ">{{ score }}% scored</p>     
											  {% endif %}
									</div>
								</div>
							</a>

						{% endif %}
					</div>
				{% endfor %}

				{% if not section_info.posttest.slug %}
				<div class="card-section " id="pretestButton" style="background-color: #FF0000;">
					<h5 style="color: white; cursor: pointer;">Contact admin: Posttest link not found</h5>
				</div>
				{% elif request.user.is_superuser %}
				<div class="card-section" style="background-color:#990033;" id="pretestButton" onclick="location.href='{% url 'preposttest:pretest' section_info.posttest.slug %}';">
					<h5 style="color: white; cursor: pointer;">Posttest admin preview. Results won't be saved</h5>
				</div>
				{% elif section_info.posttest_status == 1 %}
				<div class="card-section " style="background-color:#990033;" id="pretestButton" onclick="alertPopUp('Posttest not available as all of the quizzes is not done yet.')">
					<h5 style="color: white; cursor: pointer;">Posttest not available yet</h5>
				  </div>
				 {% elif section_info.posttest_status == 2 %}
				<div class="card-section " id="pretestButton" onclick="location.href='{% url 'preposttest:pretest' section_info.posttest.slug %}';">
					<h5 style="color: white; cursor: pointer;">Click HERE to do the posttest</h5>
				  </div>
				 {% else %}
				 <div class="card-section " id="pretestButton" onclick="alertPopUp('Posttest can only be done once')" style="background-color: #09DD91;">
					<h5 style="color: white; cursor: pointer;">POSTTEST DONE</h5>
				</div>
				{% endif %}
				  <div class="card-section " id="pretestButton" style="background-color: #F2A5A5;"onclick="location.href='{% url 'detail' %}';">
					<h5 style="color: white; cursor: pointer;">Go to details to claim your certificate</h5>
				  </div>
				</div>
	</div>
	{% endfor %}
	<!-- End of sections -->
</div>

<script>
	function alertPopUp(text) {
  	alert(text);
	}

    var disabledLinks = document.querySelectorAll('.disabledLink');
    disabledLinks.forEach(function(link) {
        link.addEventListener('click', function(event) {
            // Prevent the default behavior (navigating to a new page)
            event.preventDefault();
        });
    });

  function openSet(evt, setType) {
    var i, tabcontent, tablinks;
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
      tabcontent[i].style.display = "none";
    }
    tablinks = document.getElementsByClassName("tablinks");
    for (i = 0; i < tablinks.length; i++) {
      tablinks[i].className = tablinks[i].className.replace(" active", "");
    }
    document.getElementById(setType).style.display = "block";
    evt.currentTarget.className += " active";
  }
  
  document.addEventListener("DOMContentLoaded", function () {
    // Find with id="defaultOpen" and click on it
    document.getElementById("defaultOpen").click();
  });

  {% comment %} Smaller screen {% endcomment %}

	 function filterContent() {
	  var selectedOption = document.getElementById("sectionSelect").value;
	  var tabcontents = document.getElementsByClassName("tabcontent");
  
	  for (var i = 0; i < tabcontents.length; i++) {
		if (tabcontents[i].id === selectedOption) {
		  tabcontents[i].style.display = "block";
		} else {
		  tabcontents[i].style.display = "none";
		}
	  }
	}
  
	// Set up event listener to trigger the filtering when the dropdown value changes
	document.getElementById("sectionSelect").addEventListener("change", filterContent);
  
	// Initial filtering on page load
	filterContent(); 
  </script>
  

{% endblock content %}