src/blog/urls.py
from django.urls import path
from blog.views import(
    create_blog_view,
    detail_blog_view,
    edit_blog_view,
    quiz_view,
    quiz_data_view,
    save_quiz_view,
    bookmark_blog_view,
)

app_name = 'blog'

urlpatterns = [
    path('create/', create_blog_view, name="create"),
    path('<slug>/', detail_blog_view, name="detail"),
    path('<slug>/edit', edit_blog_view, name="edit"),
    path('<slug>/quiz', quiz_view, name="quiz"),
    path('<slug>/quiz/data', quiz_data_view, name="quiz-data"),
    path('<slug>/quiz/save', save_quiz_view, name="save-data"),
    path('<slug>/bookmark', bookmark_blog_view, name="bookmark-topic"),
]

src/mysite/urls.py
from django.contrib import admin
from django.urls import re_path, path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
  re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
  re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

from personal.views import (
    home_screen_view,
    topics_view,
    success_view,
    error_view,
    contact_view,
    privacy_view,
    faq_view,
    about_view
)

from preposttest.views import(
    pretest_view,
)

from user.views import(
    registration_view,
    login_view,
    logout_view,
    account_view,
    must_authenticate_view,
    detail_view,
    reading_view,
    cert_pdf_view,
    statistic_view,
    test_recaptcha_view,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_screen_view, name="home"),
    path('about/', about_view, name='about'),
    path('blog/', include('blog.urls','blog')),
    path('preposttest/', include('preposttest.urls','preposttest')),    
    path('register/', registration_view, name="register"),
    path('logout/', logout_view, name="logout"),
    path('login/', login_view, name="login"),
    path('account/', account_view, name="account"),
    path('accounts/', include('allauth.urls')),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('topics/', topics_view, name="topics"),
    path('detail/', detail_view, name='detail'),
    path('statistics/', statistic_view, name='statistics'),
    path('cert_pdf/<title>/', cert_pdf_view, name='cert_pdf'),
    path('reading/', reading_view, name='reading'),
    path('contact/', contact_view, name='contact'),
    path('faq/', faq_view, name='faq'),
    path('privacy/', privacy_view, name='privacy'),
    path('test-recaptcha/', test_recaptcha_view, name='test_recaptcha'),

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),

    path("success/", success_view, name="success"),
    path("error/", error_view, name="error"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/blog/models.py
from django.db import models
from django.db.models.signals import pre_save, post_delete
from django.utils.text import slugify
from django.conf import settings
from django.dispatch import receiver
from user.models import Account
import random

def upload_location(instance, filename):
    file_path = 'blog/{author_id}/{title}-{filename}'.format(
        author_id=str(instance.author.id), title=str(instance.title), filename=filename
    )
    return file_path

class Sessions(models.Model):
    title                   = models.CharField(max_length=50, null=False, blank=False)
    body                    = models.CharField(max_length=5000, null=False, blank=False)
    image                   = models.ImageField(upload_to=upload_location, null=False, blank=False)
    author                  = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    display_order           = models.IntegerField(blank=False, unique=True)

    def __str__(self):
        return self.title

    def get_blog(self):
        blog = self.blogpost_set.all().order_by('display_order')
        return blog

class BlogPost(models.Model):
    title                   = models.CharField(max_length=100, null=False, blank=False, unique=True)
    body                    = models.CharField(max_length=500000, null=False, blank=False)
    image                   = models.ImageField(upload_to=upload_location, null=False, blank=False)
    date_published          = models.DateTimeField(auto_now_add=True, verbose_name="date published")
    date_updated            = models.DateTimeField(auto_now=True, verbose_name="date updated")
    author                  = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    slug                    = models.SlugField(blank=True, unique=True)
    number_of_questions     = models.IntegerField()
    session                 = models.ForeignKey(Sessions, on_delete=models.CASCADE)
    bookmarked              = models.ManyToManyField(Account, related_name="topics", blank=True)
    display_order           = models.IntegerField(blank=False)

    def __str__(self):
        return self.title
    
    def get_questions(self):
        questions = list(self.question_set.all())
        random.shuffle(questions)
        return questions[:self.number_of_questions]
    
    def get_bookmarked_count(self):
        return self.bookmarked.count()
    
@receiver(post_delete, sender=BlogPost)
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False)

def pre_save_blog_post_receiver(sender, instance, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.author.username + "-" + instance.title)

pre_save.connect(pre_save_blog_post_receiver, sender=BlogPost)

src/blog/forms.py
from django import forms
from blog.models import BlogPost

class CreateBlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'body', 'image']

class UpdateBlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'body', 'image']

    def save(self, commit=True):
        
        blog_post = self.instance
        blog_post.title = self.cleaned_data['title']
        blog_post.body = self.cleaned_data['body']

        if self.cleaned_data['image']:
            blog_post.image = self.cleaned_data['image']

        if commit:
            blog_post.save()
        return blog_post

src/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from blog.models import BlogPost, Sessions
from preposttest.models import ResultPrePostTest
from blog.forms import CreateBlogPostForm, UpdateBlogPostForm
from user.models import Account
from django.http import JsonResponse
from question.models import Question, Answer
from answer.models import Result
import math

def bookmark_blog_view(request, slug):
    topic = get_object_or_404(BlogPost, slug = request.POST.get('blog_post_slug'))
    bookmarked = False

    if topic.bookmarked.filter(email = request.user.email).exists(): 
        bookmarked = False
        topic.bookmarked.remove(request.user)
        print("\n\n\nFOUNDDDD\nRemoved from bookmark\n\n")
    else:
        bookmarked = True
        topic.bookmarked.add(request.user)
        print("\n\n\nNOT FOUND\nAdded to bookmark\n\n")

    return HttpResponseRedirect(reverse('blog:detail', kwargs={'slug': slug}))

def create_blog_view(request):
    context = {}
    user = request.user
    if not request.user.is_staff:
        return redirect('must_authenticate')
    
    form = CreateBlogPostForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        obj = form.save(commit=False)
        author = Account.objects.filter(email=user.email).first()
        obj.author = author
        obj.save()
        form = CreateBlogPostForm()

    context['form'] = form

    return render(request, "blog/create.html", context)

def must_authenticate_view(request):
    return render(request, 'user/must_authenticate.html', {})

def detail_blog_view(request, slug):
    context = {}
    topic_selected = BlogPost.objects.get(slug=slug)
    section_content = topic_selected.session
    prev_result = 0.00

    topics = BlogPost.objects.filter(session = section_content).order_by('display_order')
    context['topics'] = topics

    if topic_selected == topics.first():
        print("\nYESS SAME\n")
        if request.user.is_authenticated:
            try:
                resultPretest = ResultPrePostTest.objects.get(pre_test__session=section_content, user=request.user, pre_test__test_type="pretest")
                prev_result = 100.00
            except ResultPrePostTest.DoesNotExist:
                prev_result = 0.00
                print("\nNOT FOUND, but 100\n")
        else:
            prev_result = 100.00
    else:
        for topic in topics:
            if topic == topic_selected :
                print("Title found:", topic_selected.title)
                break
            else:
                try:
                    if request.user.is_authenticated:
                        prev_result = Result.objects.get(user=request.user, quiz=topic).score
                    else: 
                        prev_result = 0.00
                except Result.DoesNotExist:
                    prev_result = 0.00

    print("Prev result:")
    print(prev_result)

    if prev_result != 100 and not request.user.is_authenticated:
        return redirect("topics")
    
    if prev_result != 100 and not request.user.is_admin:
        return redirect("topics")

    if request.is_ajax():
        print("request is_ajax")
        topic = request.POST.get('topicName')
        user = request.user
        return JsonResponse({'success': True})

    blog_post = get_object_or_404(BlogPost, slug=slug)
    total_likes = blog_post.get_bookmarked_count()

    bookmarked = False

    if request.user.is_authenticated:
        if blog_post.bookmarked.filter(email = request.user.email).exists(): 
            bookmarked = True

    wordCount = len(topic_selected.body.split())
    readingTime = wordCount/200

    context['reading_time'] = math.ceil(readingTime)
    context['bookmarked'] = bookmarked
    context['blog_post'] = blog_post
    context['total_likes'] = total_likes

    return render(request, 'blog/detail_blog.html', context)

def edit_blog_view(request, slug):
    user = request.user
    if not user.is_staff:
        return redirect('must_authenticate')
    
    context = {}

    blog_post = get_object_or_404(BlogPost, slug=slug)
    if request.POST:
        form = UpdateBlogPostForm(request.POST or None, request.FILES or None, instance=blog_post)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            context['success_message'] = "Topic updated"
            blog_post = obj
    
    form = UpdateBlogPostForm(
        initial={
            "title": blog_post.title,
            "body": blog_post.body,
            "image": blog_post.image,
        }
    )
    context['form'] = form
    return render(request, 'blog/edit_blog.html', context)

def quiz_view(request, slug):
    if not request.user.is_authenticated:
        return redirect('must_authenticate')
    
    quiz = BlogPost.objects.get(slug=slug)
    return render(request, 'blog/quiz.html', {'obj': quiz})

def quiz_data_view(request, slug):
    if not request.user.is_authenticated:
        return redirect('must_authenticate')
    
    quiz = BlogPost.objects.get(slug=slug)
    questions = []
    for q in quiz.get_questions():
        print(q)
        answers = []
        for a in q.get_answers():
            answers.append(a.text)
        questions.append({str(q): answers})
    return JsonResponse({
        'data': questions, 
    })

def save_quiz_view(request, slug):
    if not request.user.is_authenticated:
        return redirect('must_authenticate')
    
    print(request.POST)
    if request.is_ajax() and not request.user.is_admin:
        questions = []
        data = request.POST
        data_ = dict(data.lists())
        hasil = Result.objects.all()

        data_.pop('csrfmiddlewaretoken')
 
        for k in data_.keys():
            print('key: ', k)
            question = Question.objects.get(text=k)
            questions.append(question)
        print(questions)

        user = request.user
        quiz = BlogPost.objects.get(slug=slug)

        score = 0
        multiplier = 100 / quiz.number_of_questions
        results = []
        correct_answer = None

        for q in questions:
            a_selected = request.POST.get(q.text)

            if a_selected != "":
                question_answers = Answer.objects.filter(question=q)
                for a in question_answers:
                    if a_selected == a.text:
                        if a.correct:
                            score += 1
                            correct_answer = a.text
                    else:
                        if a.correct:
                            correct_answer = a.text

                results.append({str(q): {'correct_answer': correct_answer, 'answered': a_selected}})
            else:
                results.append({str(q): 'not answered'})

        score_ = score * multiplier

        # if user = ser now
        # results.quiz.ttle = 

        email = request.user.email

        found = False

        for x in hasil:
            if x.user.email == email:
                if x.quiz.title == quiz.title:
                    found = True
                    if x.score < score_:
                        x.delete()
                        Result.objects.create(quiz=quiz, user=user,score=score_)
                        print(x.score)
                        print(score_)

        if found == False:
            Result.objects.create(quiz=quiz, user=user,score=score_)

        if score_ == 100 :
            return JsonResponse({'passed': True, 'score': score_, 'results': results})
        else:
            return JsonResponse({'passed': False, 'score': score_, 'results': results})

src/blog/templates/blog/create.html
{% extends 'base.html' %}

{% block content %}

<style type="text/css">
    .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}
    .create-form input[type="text"] {
        margin-bottom: 10px;
        border-top-left-radius: 25px;
        border-top-right-radius: 25px;
        border-bottom-right-radius: 25px;
        border-bottom-left-radius: 25px;
    }
  	.submit-button{
  		max-width: 200px;
        border-top-left-radius: 25px;
        border-top-right-radius: 25px;
        border-bottom-right-radius: 25px;
        border-bottom-left-radius: 25px;
  	}
</style>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">
			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				<!-- title -->
				<div class="form-group">
					<label for="id_title">Title</label>
					<input class="form-control" type="text" name="title" id="id_title" placeholder="Title" required autofocus>
				</div>

				<!-- Body -->
				<div class="form-group">
					<label for="id_body">Content</label>
					<textarea class="form-control" rows="10" type="text" name="body" id="id_body" placeholder="This blog is about..." required></textarea>
				</div>

				<!-- Image -->
				<div class="form-group">
					<label for="id_image">Image</label>
					<input  type="file" name="image" id="id_image" accept="image/*" required>
				</div>

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">POST</button>
			</form>	
		</div>
	</div>
</div>

{% endblock content %}

src/blog/templates/blog/detail_blog.html
{% extends 'base.html' %}
{% load static %}
{% block scripts %}
  <script src="{% static 'quizes/detail.js'%}" defer></script>

{% endblock scripts%}

{% block title %}

{{obj.name}}
{% endblock title %}
{% block content %}

<title>{{ blog_post.title }} - Dementia Learn</title>

<style type="text/css">
    .card{
        padding: 20px;  
        box-shadow: 0 1px 2px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
    }
    .image{
        height: 100vh;
        object-fit: cover;
    }
.navbar{
    background-color: #000000c3;
        box-shadow: 0px 0px 10px #a2a2a27b;
    }


    .bayangan{
        box-shadow: 0px -15px 30px #a2a2a239;
    }

    .sticky1 {
        overflow: hidden;
        position: -webkit-sticky;
        position: sticky;
        top: 10%;
        /* padding: 80px; */
        font-size: 20px;
    }

    #progress-bar {
    --scrollAmount: 0%;
    
    background-image: linear-gradient(120deg, #84fab0 0%, #8fd3f4 100%);
    width: var(--scrollAmount);
    z-index: 2;
    
    height: 15px;
    position: fixed;
    top: 0;
}
.wrapper{
    display: flex;
    width: 100%;
}
article{
    counter-reset: heading;
}
article h2::before{
    counter-increment: heading;
    content: '0'counter(heading)': ';
}
#toc h2 {
    text-transform: uppercase;
    font-size: 11pt;
    letter-spacing: 2px;
}
#toc h3 {
    font-weight: normal;
    font-size: inherit;
}

.btn-circle.btn-xl {
    width: 100px;
    height: 100px;
    padding: 13px 18px;
    border-radius: 60px;
    font-size: 15px;
    text-align: center;
}
.contentWrapper{
    padding: 4vw; 
    margin-top:-200px; 
    background-color: white; 
    min-height: 100%; 
    margin-left:10px;  
    max-width: 65%; 
    margin-bottom: 50px;
}
.rightCornerBookmark{
    text-align: center; 
    right: 0; 
    top: 0; 
    position: absolute;
}
  @media only screen and (max-width: 800px) {
    .wrapper{
        display: block;
    }
    .contentWrapper{
        max-width: 100%; 
        margin-right: 20px;
        margin-bottom: 0px;
        position: relative;
    }
    .displayOrNot{
        display: none;
    }
    .sticky1{
        margin-bottom: 10px;
    }
    .remove{
        display: none;
    }
    
  }
  @media only screen and (min-width: 801px) {
    .rightCornerBookmark{
        display: none;
    }
  }
</style>
<template>
    <ul>
        <li style="padding-bottom: 5px;"><a href='#h-1'><slot name='h-1'></slot></a></li>
        <li style="padding-bottom: 5px;"><a href='#h-2'><slot name='h-2'></slot></a></li>
        <li style="padding-bottom: 5px;"><a href='#h-3'><slot name='h-3'></slot></a></li>
        <li style="padding-bottom: 5px;"><a href='#h-4'><slot name='h-4'></slot></a></li>
        <li style="padding-bottom: 5px;"><a href='#h-5'><slot name='h-5'></slot></a></li>
        <li style="padding-bottom: 5px;"><a href='#h-6'><slot name='h-6'></slot></a></li>
        <li style="padding-bottom: 5px;"><a href='#h-7'><slot name='h-7'></slot></a></li>
    </ul>
    <style>
        ul{
            list-style: none;
        }
        ul:not(li>ul){
            padding-left: 0;
        }
        a:link {
            color: inherit;
        }
    </style>
</template>

<script src="{% static 'app.js' %}" defer></script>
<div id="progress-bar" style="margin-top: 75px; "></div>

<div class="container-fluid p-0 m-0" style="background-color: #F5F5F5;"> 
    <div class = "image" style="background-image: url('{{blog_post.image.url}}'); background-size: cover; width: 100%; margin-top: -100px; padding-top: 50vh; background-repeat: no-repeat;"> 
    </div> 
    
    <div class="wrapper">
        
        <div class="remove"style="text-align: center; margin-top: 20px;">
            {% if user.is_authenticated %}
                <form action="{% url 'blog:bookmark-topic' blog_post.slug %}" method="POST" style="color:white;">
                    {% csrf_token %}
                    {% if not bookmarked %}
                    <button type="submit" name="blog_post_slug" class="btn-circle btn-xl" style="border:none; background-color: #F5F5F5" value="{{ blog_post.slug }}">
                        <img src="https://live.staticflickr.com/65535/53061171761_11446e3bc9_m.jpg" style="width: 100%;">
                    </button> 
                    {% else %}
                    <button type="submit" name="blog_post_slug" class="btn-circle btn-xl" style="border:none; background-color: #F5F5F5" value="{{ blog_post.slug }}">
                        <img src="https://live.staticflickr.com/65535/53060606667_0f74dbfdfb_m.jpg" style="width: 100%;">

                    </button> 
                    {% endif %}
                </form>
            <h6 style="color: #6D7D8B;">{{ total_likes }}</h6>
            {% else %}
                <div style="width: 30px;">
                </div>
            {% endif %}
        </div>


        <div class="card contentWrapper">
            <p style="color: #6d6d6d; font: 10px;">{{blog_post.date_updated}}<p>
            <p class="font-weight-bold" style="font-size: 50px; margin-top: -30px;">{{blog_post.title}}</p>
                <p class="text-muted" style="font-size: 17px;">By {{blog_post.author}} - around {{ reading_time }} minutes read time</p>
                <div class="rightCornerBookmark">
                    {% if user.is_authenticated %}
                    <form action="{% url 'blog:bookmark-topic' blog_post.slug %}" method="POST" style="color:white;">
                        {% csrf_token %}
                        {% if not bookmarked %}
                        <button type="submit" name="blog_post_slug" class="btn-circle btn-xl" style="border:none; background-color: white" value="{{ blog_post.slug }}">
                            <img src="https://live.staticflickr.com/65535/53083360176_f713a97295_m.jpg" style="width: 100%;">
                        </button> 
                        {% else %}
                        <button type="submit" name="blog_post_slug" class="btn-circle btn-xl" style="border:none; background-color: white" value="{{ blog_post.slug }}">
                            <img src="https://live.staticflickr.com/65535/53083845313_0a01c01a23_m.jpg" style="width: 100%;">
            
                        </button> 
                        {% endif %}
                    </form>
                    <h6 style="color: #6D7D8B;">{{ total_likes }}</h6>
                    {% endif %}
                </div>            <hr>
            {% if request.user.is_superuser %}
                <a href="{% url 'blog:edit' blog_post.slug %}" class="btn btn-primary">Update</a>
            {% endif %}

            <article>
                <div id='toc1' ></div>
                <p class="card-text mt-2">{{blog_post.body|safe}}</p>
            </article>
    
        </div>
        <div>
            {% if user.is_authenticated and not user.is_superuser %}
                <div class="sticky1" style="margin-right: 12px">
                    <div class="sticky1" style=" margin-top: 10px; margin-left: 12px; margin-right: 12px" >
                        <div class="card" style="margin-bottom: 15px; min-width: 22vw;">
                            <h6 style="padding-bottom: 10px;">Try our quiz</h6>
                            <a class=" btn " href="quiz" style="color:white; background: #0C6DFD;">TRY NOW!</a>
                        </div>
                    </div>
                    <div class="sticky1 displayOrNot" style=" margin-top: 45px; margin-left: 12px; margin-right: 12px;" >
                        <div class="card" style="margin-bottom: 15px; min-width: 22vw;">
                            <div id='toc'></div>
                        </div>
                    </div>
                </div>
            {% elif user.is_superuser %}
                <div class="sticky1" style="margin-right: 12px">
                    <div class="sticky1" style=" margin-top: 10px; margin-left: 12px; margin-right: 12px" >
                        <div class="card" style="margin-bottom: 15px; min-width: 22vw;">
                            <h6 style="color: #991A36; padding-bottom: 10px;">Admin preview, results won't be saved</h6>
                            <a class=" btn " href="quiz" style="color:white; background: #991A36;">Open quiz preview</a>
                        </div>
                    </div>
                    <div class="sticky1 displayOrNot" style=" margin-top: 45px; margin-left: 12px; margin-right: 12px;" >
                        <div class="card" style="margin-bottom: 15px; min-width: 22vw;">
                            <div id='toc'></div>
                        </div>
                    </div>
                </div>
            {% else %}
                <div class="sticky1" style="margin-right: 12px">
                    <div class="sticky1" style=" margin-top: 17px; margin-left: 12px; margin-right: 12px;" >
                        <div class="card" style="margin-bottom: 15px; min-width: 22vw;">
                            <h6 style="padding-bottom: 10px;">Sign in or sign up now to try out the quiz</h6>
                            <a class=" btn btn-primary" href="{% url 'register' %}" style="color:white;">SIGN UP NOW!</a>
                        </div>
                    </div>
                    <div class="sticky1 displayOrNot" style=" margin-top: 45px; margin-left: 12px; margin-right: 12px;" >
                        <div class="card" style="margin-bottom: 15px; min-width: 22vw;">
                            <div id='toc'></div>
                        </div>
                    </div>
                </div>
            {% endif %}

                    
            
        </div>
        
        
    </div>
</div>


<script>
    if('name' in document.createElement('slot') && 'attachShadow' in document.createElement('p')) {
        let templateContent = document.querySelector('template').content;
        let article = document.querySelector('article').cloneNode(true);
        article.querySelectorAll('*[id]').forEach((ele)=>{ele.removeAttribute('id')})
        article.attachShadow({  mode: 'closed' }).appendChild(templateContent.cloneNode(true));
        document.querySelector('#toc').appendChild(article);
    }
    else{
        let strong = document.createElement('strong');
        strong.textContent = '⚠️ HTML Slot or Shadow DOM is not supported in your browser. Please try the demo in another browser.';
        strong.style['color'] = 'red';
        document.body.insertBefore(strong, document.querySelector('h1'))
    }
    </script>

{% endblock content %}

src/blog/templates/blog/edit_blog.html
{% extends 'base.html' %}


{% block content %}
<style type="text/css">
   .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}
body {
   
    background-image: linear-gradient(135deg, #e69d57 10%, #ffd4d4 100%);
  }
  	.submit-button{
  		max-width: 200px;
  	}

	.image {
	  opacity: 1;
	  transition: .5s ease;
	  backface-visibility: hidden;
	}

	.middle {
	  transition: .5s ease;
	  opacity: 0;
	  position: absolute;
	  text-align: center;
	  top: 50%;
	  left: 50%;
	  transform: translate(-50%, -50%);
	
	}
	.image-group{
		position: relative;
  		text-align: center;
  		cursor:pointer;
	}

	.image-group:hover .image {
	  opacity: 0.3;
	}

	.image-group:hover .middle {
	  opacity: 1;
	}

	.text {
	  margin: auto;
	  background-color: #4CAF50;
	  color: white;
	  font-size: 15px;
	  padding: 15px;
	}
</style>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">

			{% if success_message %}
				<h3 style="color:green; text-align: center;">{{success_message}}</h3>
			{% endif %}

			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				<!-- title -->
				<div class="form-group">
					<label for="id_title">Title</label>
					<input class="form-control" type="text" name="title" id="id_title" placeholder="Title" value="{{form.initial.title}}" required autofocus>
				</div>

				<!-- Body -->
				<div class="form-group">
					<label for="id_body">Content</label>
					<textarea class="form-control" rows="10" type="text" name="body" id="id_body" placeholder="This blog is about..." 
					required>{{form.initial.body}}</textarea>
				</div>

				<!-- Image -->
				<div class="form-group image-group" id="id_image_group">
					<img class="img-fluid image" src="{{form.initial.image.url}}" id="id_image_display">
					  <div class="middle">
					    <div class="text">Change image</div>
					  </div>
				</div>
				<input type="file" name="image" id="id_image_file" accept="image/*" onchange="readURL(this)">
				

				{% for field in form %}
					<p>
						{% for error in field.errors %}
							<p style="color: red">{{ error }}</p>
						{% endfor %}
					</p>
				{% endfor %}
				{% if form.non_field_errors %}
					<div style="color: red">
						<p>{{form.non_field_errors}}</p>
					</div>
				{% endif %}

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Update</button>
			</form>	
		</div>
	</div>
</div>

<script type="text/javascript">
	document.getElementById('id_image_group').onclick = function(event){
    	document.getElementById('id_image_file').click();
    };

	function readURL(input){
		var reader = new FileReader();
		reader.onload = function (e) {
            $('#id_image_display')
                .attr('src', e.target.result)
        };
		reader.readAsDataURL(input.files[0]);
	}
</script>

{% endblock content %}